// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rspsJVUOk9JIYjWvYzC9sMg946DINZ4',
    appId: '1:758202431270:web:cd41819c67e344e1f533e7',
    messagingSenderId: '758202431270',
    projectId: 'connectcarechatbot',
    authDomain: 'connectcarechatbot.firebaseapp.com',
    storageBucket: 'connectcarechatbot.firebasestorage.app',
    measurementId: 'G-10WP41DBCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1yAg9J5kTo7d342ON1igeGnKUy83ATU',
    appId: '1:758202431270:android:cac5710543681f7df533e7',
    messagingSenderId: '758202431270',
    projectId: 'connectcarechatbot',
    storageBucket: 'connectcarechatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKY3ImHYc-KTF6iRezy4cQc9VXI3hbcU',
    appId: '1:758202431270:ios:966346b666c1fd06f533e7',
    messagingSenderId: '758202431270',
    projectId: 'connectcarechatbot',
    storageBucket: 'connectcarechatbot.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCKY3ImHYc-KTF6iRezy4cQc9VXI3hbcU',
    appId: '1:758202431270:ios:966346b666c1fd06f533e7',
    messagingSenderId: '758202431270',
    projectId: 'connectcarechatbot',
    storageBucket: 'connectcarechatbot.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5rspsJVUOk9JIYjWvYzC9sMg946DINZ4',
    appId: '1:758202431270:web:7bc08a8d1342a0cff533e7',
    messagingSenderId: '758202431270',
    projectId: 'connectcarechatbot',
    authDomain: 'connectcarechatbot.firebaseapp.com',
    storageBucket: 'connectcarechatbot.firebasestorage.app',
    measurementId: 'G-E5H3TJYCPM',
  );

}