// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5cvP2Z-8m3sYl1uHZvHxw1cAt96y_Vc',
    appId: '1:402930455357:web:0ec51d2855ff7d6e146b54',
    messagingSenderId: '402930455357',
    projectId: 'push-notifications-cb0f9',
    authDomain: 'push-notifications-cb0f9.firebaseapp.com',
    storageBucket: 'push-notifications-cb0f9.firebasestorage.app',
    measurementId: 'G-B650Y6YE5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0EWuBDqX48ucJA_EY6Wasg-p1-kn-F4',
    appId: '1:402930455357:android:013929183fc2ee84146b54',
    messagingSenderId: '402930455357',
    projectId: 'push-notifications-cb0f9',
    storageBucket: 'push-notifications-cb0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfoKo-33EYefALr9PvAc7Hr4dzBnQ8vG8',
    appId: '1:402930455357:ios:98f02a7ac9b28fbf146b54',
    messagingSenderId: '402930455357',
    projectId: 'push-notifications-cb0f9',
    storageBucket: 'push-notifications-cb0f9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfoKo-33EYefALr9PvAc7Hr4dzBnQ8vG8',
    appId: '1:402930455357:ios:98f02a7ac9b28fbf146b54',
    messagingSenderId: '402930455357',
    projectId: 'push-notifications-cb0f9',
    storageBucket: 'push-notifications-cb0f9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM5cvP2Z-8m3sYl1uHZvHxw1cAt96y_Vc',
    appId: '1:402930455357:web:468d6528601411e4146b54',
    messagingSenderId: '402930455357',
    projectId: 'push-notifications-cb0f9',
    authDomain: 'push-notifications-cb0f9.firebaseapp.com',
    storageBucket: 'push-notifications-cb0f9.firebasestorage.app',
    measurementId: 'G-48ESL3EPN0',
  );
}
