import 'package:flutter/material.dart';
import 'package:flutter_app_stable/screens.dart';
import 'package:go_router/go_router.dart';

part 'pages.g.dart';

/// Defines the methods that will be generated by the generator.
///
/// It could be part of `go_router`.
abstract class GoRouteDataImpl {
  String get location;

  void go(BuildContext context);
}

@TypedGoRoute<HomeRoute>(
  path: '/',
  routes: [
    TypedGoRoute<FamilyRoute>(
      path: 'family/:fid',
      routes: [
        TypedGoRoute<PersonRoute>(
          path: 'person/:pid',
        ),
      ],
    ),
  ],
)
class HomeRoute extends GoRouteData {
  const HomeRoute();

  @override
  Widget build(BuildContext context) => const HomeScreen();
}

class FamilyRoute extends GoRouteData {
  const FamilyRoute({
    required this.fid,
  });

  final String fid;

  @override
  Widget build(BuildContext context) => FamilyScreen(fid: fid);
}

class PersonRoute extends GoRouteData {
  const PersonRoute({
    required this.fid,
    required this.pid,
  });
  final String fid;
  final String pid;

  @override
  Widget build(BuildContext context) => PersonScreen(fid: fid, pid: pid);
}
